2024-04-09 22:39:58,910 INFO    MainThread:41497 [wandb_setup.py:_flush():76] Current SDK version is 0.16.5
2024-04-09 22:39:58,910 INFO    MainThread:41497 [wandb_setup.py:_flush():76] Configure stats pid to 41497
2024-04-09 22:39:58,910 INFO    MainThread:41497 [wandb_setup.py:_flush():76] Loading settings from /home/wang4538/.config/wandb/settings
2024-04-09 22:39:58,910 INFO    MainThread:41497 [wandb_setup.py:_flush():76] Loading settings from /home/wang4538/DGMS-master/wandb/settings
2024-04-09 22:39:58,911 INFO    MainThread:41497 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-09 22:39:58,911 INFO    MainThread:41497 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-04-09 22:39:58,911 INFO    MainThread:41497 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'main.py', 'program_abspath': '/home/wang4538/DGMS-master/main.py', 'program': '/home/wang4538/DGMS-master/main.py'}
2024-04-09 22:39:58,911 INFO    MainThread:41497 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-04-09 22:39:58,911 INFO    MainThread:41497 [wandb_init.py:_log_setup():527] Logging user logs to /home/wang4538/DGMS-master/wandb/run-20240409_223958-e7ryp9k0/logs/debug.log
2024-04-09 22:39:58,911 INFO    MainThread:41497 [wandb_init.py:_log_setup():528] Logging internal logs to /home/wang4538/DGMS-master/wandb/run-20240409_223958-e7ryp9k0/logs/debug-internal.log
2024-04-09 22:39:58,911 INFO    MainThread:41497 [wandb_init.py:init():567] calling init triggers
2024-04-09 22:39:58,911 INFO    MainThread:41497 [wandb_init.py:init():574] wandb.init called with sweep_config: {}
config: {}
2024-04-09 22:39:58,911 INFO    MainThread:41497 [wandb_init.py:init():617] starting backend
2024-04-09 22:39:58,911 INFO    MainThread:41497 [wandb_init.py:init():621] setting up manager
2024-04-09 22:39:58,912 INFO    MainThread:41497 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-04-09 22:39:58,914 INFO    MainThread:41497 [wandb_init.py:init():629] backend started and connected
2024-04-09 22:39:58,916 INFO    MainThread:41497 [wandb_init.py:init():721] updated telemetry
2024-04-09 22:39:58,927 INFO    MainThread:41497 [wandb_init.py:init():754] communicating run to backend with 90.0 second timeout
2024-04-09 22:39:59,109 INFO    MainThread:41497 [wandb_run.py:_on_init():2344] communicating current version
2024-04-09 22:39:59,183 INFO    MainThread:41497 [wandb_run.py:_on_init():2353] got version response upgrade_message: "wandb version 0.16.6 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-04-09 22:39:59,183 INFO    MainThread:41497 [wandb_init.py:init():805] starting run threads in backend
2024-04-09 22:40:02,608 INFO    MainThread:41497 [wandb_run.py:_console_start():2323] atexit reg
2024-04-09 22:40:02,609 INFO    MainThread:41497 [wandb_run.py:_redirect():2178] redirect: wrap_raw
2024-04-09 22:40:02,609 INFO    MainThread:41497 [wandb_run.py:_redirect():2243] Wrapping output streams.
2024-04-09 22:40:02,609 INFO    MainThread:41497 [wandb_run.py:_redirect():2268] Redirects installed.
2024-04-09 22:40:02,610 INFO    MainThread:41497 [wandb_init.py:init():848] run started, returning control to user process
2024-04-09 22:40:02,842 INFO    MainThread:41497 [wandb_run.py:_config_callback():1347] config_cb None None {'composer_version': '0.17.2'}
2024-04-09 22:40:02,843 INFO    MainThread:41497 [wandb_run.py:_config_callback():1347] config_cb None None {'composer_commit_hash': 'None'}
2024-04-09 22:40:02,843 INFO    MainThread:41497 [wandb_run.py:_config_callback():1347] config_cb None None {'num_nodes': 1, 'num_gpus_per_node': 1, 'node_name': 'unknown because NODENAME environment variable not set'}
2024-04-09 22:40:02,843 INFO    MainThread:41497 [wandb_run.py:_config_callback():1347] config_cb None None {'rank_zero_seed': 1}
2024-04-09 22:40:03,212 INFO    MainThread:41497 [wandb_run.py:_config_callback():1347] config_cb None None {}
2024-04-09 22:40:11,312 WARNING MsgRouterThr:41497 [router.py:message_loop():77] message_loop has been closed
